<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaseIntegracao.Application\CaseIntegracao.Application.csproj" />
    <ProjectReference Include="..\CaseIntegracao.Infrastructure\CaseIntegracao.Infrastructure.csproj" />
    <ProjectReference Include="..\CaseIntegracao.Domain\CaseIntegracao.Domain.csproj" />
  </ItemGroup>

</Project>
